[project]
name = "comfyui-dapao-tool"
description = "ğŸ­ å¤§ç‚®-Qwen3VL ComfyUI è‡ªå®šä¹‰èŠ‚ç‚¹é›†åˆï¼Œé›†æˆäº†é˜¿é‡Œäº‘ Qwen å›¢é˜Ÿå¼€å‘çš„ Qwen3-VL å¤šæ¨¡æ€å¤§è¯­è¨€æ¨¡å‹ç³»åˆ—ã€‚"
version = "1.0.3"
license = { file = "LICENSE" }

[project.urls]
Repository = "https://github.com/paolaoshi/ComfyUI-Qwen3VL-DP"

[tool.comfy]
PublisherId = "paolaoshi"
DisplayName = "å¤§ç‚®-Qwen3VL"
Icon = ""
Banner = ""

